version: "3"
services:
  daily:
    build:
      context: ./docker
      dockerfile: Dockerfile
    ports:
      - 5312:8081
    depends_on:
      - mysql
    links:
      - mysql:mysql
    volumes:
      - ./:/root/app
      - ./docker/wait-for-it.sh:/root/wait-for-it.sh
    command: /bin/bash -c  "chmod +x /root/wait-for-it.sh;/root/wait-for-it.sh mysql:3306 -- echo mysql launch success;cd /root/app;air"
  mysql:
    build:
      context: ./docker
      dockerfile: ./mysql/Dockerfile
    ports:
      - 1232:3306
    security_opt:
      - seccomp:unconfined
    restart: always
    volumes:
      - ./docker:/root/mysql
    environment:
      - MYSQL_ALLOW_EMPTY_PASSWORD=false
      - MYSQL_ROOT_PASSWORD=sukeaiya
      - LANG=C.UTF-8
      - default_authentication_plugin=mysql_native_password
      - character-set-server=utf8mb4
      - collation-server=utf8mb4_unicode_ci
