version: "3"
services:
  dev:
    build:
      context: ./
      dockerfile: Dockerfile
    restart: always
    ports:
      - 5321:9871
    volumes:
      - ./:/root/app
    command: /bin/bash -c 'cd /root/app;python manage.py colletcstatic;uwsgi uwsgi.ini'
