# Generated by Django 3.1.3 on 2020-11-08 03:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('describe', models.CharField(max_length=500)),
                ('start', models.DateField(verbose_name='start_time')),
                ('expectedEnd', models.DateField(verbose_name='expected_end_time')),
                ('actualDeliveryDate', models.DateField(verbose_name='actual_delivery_date')),
                ('createdAt', models.DateTimeField(verbose_name='created_at')),
                ('updatedAt', models.DateTimeField(verbose_name='updated_at')),
            ],
        ),
        migrations.CreateModel(
            name='Logs',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField(max_length=500)),
                ('createdAt', models.DateTimeField(verbose_name='created_at')),
                ('updatedAt', models.DateTimeField(verbose_name='updated_at')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='todo.project')),
            ],
        ),
    ]
