basePath: /
definitions:
  gorm.DeletedAt:
    properties:
      time:
        type: string
      valid:
        description: Valid is true if Time is not NULL
        type: boolean
    type: object
  models.ProjectLogModel:
    properties:
      content:
        type: string
      created_at:
        type: string
      deleted_at:
        $ref: '#/definitions/gorm.DeletedAt'
      id:
        type: integer
      plus_progress:
        type: integer
      project_id:
        type: integer
      updated_at:
        type: string
    type: object
  models.ProjectModel:
    properties:
      actual_delivery_date:
        $ref: '#/definitions/utils.JSONTime'
      created_at:
        type: string
      deleted_at:
        $ref: '#/definitions/gorm.DeletedAt'
      describe:
        type: string
      expect_end:
        $ref: '#/definitions/utils.JSONTime'
      id:
        type: integer
      logs:
        items:
          $ref: '#/definitions/models.ProjectLogModel'
        type: array
      name:
        type: string
      progress:
        type: integer
      start:
        $ref: '#/definitions/utils.JSONTime'
      updated_at:
        type: string
    type: object
  utils.JSONTime:
    properties:
      time.Time:
        type: string
    type: object
info:
  contact:
    email: support@swagger.io
    name: API Support
    url: http://www.swagger.io/support
  description: This is a sample server Petstore server.
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html
  termsOfService: http://swagger.io/terms/
  title: simple-daily
  version: "1.0"
paths:
  /project/update/{id}:
    put:
      consumes:
      - application/json
      description: get accounts
      parameters:
      - description: 项目ID
        in: path
        name: id
        required: true
        type: string
      - description: 更新
        in: body
        name: body
        required: true
        schema:
          $ref: '#/definitions/models.ProjectModel'
      produces:
      - application/json
      summary: List accounts
swagger: "2.0"
