# Generated by Django 3.1.3 on 2020-11-08 20:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0003_project_progress'),
    ]

    operations = [
        migrations.AddField(
            model_name='log',
            name='plusProgress',
            field=models.IntegerField(default=0, verbose_name='plus_progress'),
        ),
    ]
